services:
  mongo-primary:
    image: mongo:7
    container_name: mongo-primary
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-primary:/data/db
    healthcheck:
      test: |
        echo 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "127.0.0.1:27017"}]})' | mongosh --quiet || echo 'rs.status()' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    name: "mongo-cluster"
    driver: bridge
